# Generated by Django 5.1.3 on 2025-02-15 22:07

import django.db.models.deletion
import djangocms_text.fields
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=False, verbose_name='Veröffentlicht')),
                ('title', models.CharField(max_length=100, verbose_name='Titel')),
                ('content', djangocms_text.fields.HTMLField()),
                ('image_thumbnail', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Bild einfügen')),
                ('tags', models.ManyToManyField(to='projects.choice', verbose_name='Tags auswählen')),
            ],
        ),
    ]
