# Generated by Django 5.1.3 on 2025-02-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectRelease',
        ),
    ]
