# Generated by Django 5.1.3 on 2025-02-18 18:00

import django.db.models.deletion
import djangocms_text.fields
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_delete_projectrelease'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titel eingeben')),
                ('description', djangocms_text.fields.HTMLField(verbose_name='Content eingeben')),
                ('repository_link', models.URLField(verbose_name='Github Link')),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Bild einfügen')),
                ('tag', models.ManyToManyField(related_name='project_items', to='projects.choice')),
            ],
        ),
    ]
