# Generated by Django 5.1.3 on 2025-02-15 16:19

import django.db.models.deletion
import djangocms_text.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('content', djangocms_text.fields.HTMLField()),
                ('title', models.CharField(max_length=100, verbose_name='Titel eingeben')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
